# Don't forgot to run `npm run build` before running `docker-compose up -d`, If you have any changes in the frontend.

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html/watch-sync
  broadcast:
    build:
      context: ./docker/broadcast
      dockerfile: Dockerfile
    container_name: broadcast
    volumes:
      - ./src:/watch-sync
  web:
    image: nginx:1.25.1-alpine-slim
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html/watch-sync
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:8.0.34
    container_name: mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
