import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";

import { Box, ColorSchemeScript, MantineProvider } from "@mantine/core";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Notifications } from "@mantine/notifications";
import { Providers } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider>
          <Notifications />
          <Box bg={"gray.0"}>
            <Providers>{children}</Providers>
          </Box>
        </MantineProvider>
      </body>
    </html>
  );
}
